language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/.npm"
script:
- travis_wait 30 npm run nx affected:lint -- --all
- travis_wait 30 npm run nx format:check
- travis_wait 30 npm run nx affected:build -- --all --prod
- travis_wait 30 npm run nx affected:test -- --all

before_deploy:
- openssl aes-256-cbc -K $encrypted_73a04b219ad5_key -iv $encrypted_73a04b219ad5_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: master
