version: '3'
services:

  # Frontend
  frontend:
    build:
      context: ./
      dockerfile: .docker/frontend.dockerfile
    working_dir: /home/node
    volumes:
      - ./:/home/node
    ports:
      - 4200:4200