version: 2
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - dependencies
      - test-lint:
          requires:
            - dependencies
      - test-format:
          requires:
            - dependencies
      - test-build:
          requires:
            - dependencies
      - test-test:
          requires:
            - dependencies
      - test-e2e:
          requires:
            - dependencies
            - test-lint
            - test-format
            - test-build
            - test-test
jobs:
  dependencies:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

  test-lint:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn nx affected:lint --all

  test-format:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn nx format:check

  test-build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn affected:build --all --prod --no-progress
      - save_cache:
          paths:
            - dist
          key: dist-{{ .Revision }}

  test-e2e:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: ./node_modules/.bin/webdriver-manager update
      - run: yarn nx affected:e2e --all --prod --no-progress

  test-test:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies-
      - run: yarn affected:test --all --no-progress
