version: 2
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - dependencies
      - test-lint
        requires:
          - dependencies
      - test-format
        requires:
          - dependencies
      - test-build
        requires:
          - dependencies
      - test-test
        requires:
          - dependencies
      # deploy requires approval
jobs:
  dependencies:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

  test-lint:
    docker:
      - image: circleci/node:10-browsers

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm run nx affected:test -- --all

  test-format:
    docker:
      - image: circleci/node:10-browsers

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm run nx format:check

  test-build:
    docker:
      - image: circleci/node:10-browsers

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm run nx affected:build -- --all --prod

  test-test:
    docker:
      - image: circleci/node:10-browsers

      working_directory: ~/repo

      steps:
        - checkout
        - run: npm run affected:test -- --all
