name: Verseghy CI
on: [push]

jobs:
  lint:
    name: Test Linting
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v1
      - name: "Run yarn install"
        run: yarn nx affected:lint --all

strategy:
  matrix:
    node: [12]
    os: [macOS-latest, windows-latest, ubuntu-latest]
