name: Verseghy CI
on:
  pull_request:
    paths:
      - 'apps/frontend/**'
      - 'package.json'
      - 'yarn.lock'
      - 'angular.json'

jobs:
  frontend-deploy-dev:
    name: Deploy preview site
    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup dependencies
        run: yarn

      - name: Build
        run: yarn build frontend --no-progress

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VFG_HONLAP }}'
          projectId: vfg-honlap
          expires: 3d
          entryPoint: 'apps/frontend'
          channelId: '${{ github.ref }}'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
